config/routes.rb
Rails.application.routes.draw do
  get 'inquiry/index'
  get 'inquiry/confirm'
  get 'inquiry/thanks'
  #twitter認証
  get '/auth/:provider/callback', to: 'sessions#create', as: 'auth_login'
  get '/logout', to: 'sessions#destroy'

  #静的ページRoutes
  root "static_pages#home"
  get '/terms' ,to: "static_pages#terms" 
  get '/privacy', to: "static_pages#privacy"
  
  get '/inquiry', to: 'inquiry#index'              # 入力画面
  post '/inquiry/confirm', to: 'inquiry#confirm'   # 確認画面
  post '/inquiry/thanks', to: 'inquiry#thanks'     # 送信完了画面

  #ユーザのRoutes
  resources :users, param: :nickname, only: [:new, :show, :destroy] do
    resources :posts, param: :slug do
      member do
        patch :published_true
        patch :published_false
      end
    end
  end

end

app/models/user.rb
class User < ApplicationRecord

  has_many :posts, dependent: :destroy  #userが削除されると所有しているpostsも削除される

  #twitter認証
  def self.find_or_create_from_auth(auth)
    provider = auth[:provider]
    uid = auth[:uid]
    name = auth[:info][:name]
    nickname = auth[:info][:nickname]
    image_url = auth[:info][:image]

    self.find_or_create_by(provider: provider, uid: uid) do |user|
      user.name = name
      user.nickname = nickname
      user.image_url = image_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #ユーザ削除(destroy)は本人のみ
  before_action :correct_user, only: :destroy
  
  def show
    @user = User.find_by(nickname: params[:nickname])
    @posts = @user.posts.all.order(created_at: "DESC")
  end

  def new
  end

  #def index 
  #  @users = User.all
  #end

  def destroy
    #correct_userで@user取得
    @user.destroy
    session[:user_id] = nil #sessionも削除

    flash[:success] = "ユーザを削除しました"
    redirect_to root_path
  end

  private

    #current_userが@userと一致するか
    def correct_user
      @user = User.find_by(nickname: params[:nickname])
      unless current_user?(@user) then
        flash[:danger] = "あなたは#{@user.nickname}ではありません"
        redirect_to user_path(@user.nickname)
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_public.html.erb
<%# 公開ON時 %>

<%# Ajaxの場合のpost,user取得 %>
<% post ||= @post %>
<% user ||= @user %>

<%# 公開ボタン描画 %>
<%= form_for(post, url: published_false_user_post_path(user.nickname, post.slug), remote: true) do |f| %>
  <%= button_tag type: 'submit', class: 'btn btn-success btn-squared btn-unlock' do %>
    <i class="fa fa-unlock fa-lg"></i>
  <% end %><!-- 
  --><%= button_tag type: 'submit', class: 'btn btn-light btn-squared text-white btn-lock' do %>
    <i class="fa fa-lock fa-lg"></i>
  <% end %>
<% end %>

app/views/users/_unpublic.html.erb
<%# 公開OFF時 %>

<%# Ajaxの場合のpost,user取得 %>
<% post ||= @post %>
<% user ||= @user %>

<%# 非公開ボタン描画 %>
<%= form_for(post, url: published_true_user_post_path(user.nickname, post.slug), remote: true) do |f| %>
  <%= button_tag type: 'submit', class: 'btn btn-light btn-squared text-white btn-unlock' do %>
    <i class="fa fa-unlock fa-lg"></i>
  <% end %><!-- 
--><%= button_tag type: 'submit', class: 'btn btn-secondary btn-squared btn-lock' do %>
    <i class="fa fa-lock fa-lg"></i>
  <% end %>
<% end %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="profile-card card col-md-3 mt-4 mb-4">
      <%= image_tag @user.image_url, size:"64x64", alt:"profile img", class:"mt-3 ml-3"%>
      <div class="card-body">
        <div class="card-title">
          <%= @user.name %>
        </div>
        <%= link_to '新規投稿', new_user_post_path(@user.nickname), class:"btn btn-primary mt-2" if current_user?(@user) %><br>
        <%= link_to 'ユーザ削除', user_path(@user.nickname), method: :delete, 
          data: {confirm: "#{@user.nickname}を削除します。よろしいですか？(投稿も全て削除されます)"}, class:"btn btn-danger mt-2" if current_user?(@user) %>
      </div>
    </div>

    <div class="col-md-8 offset-md-1 mt-4 mb-4">
      <h2>投稿一覧</h2>
      <%#投稿がないとき%>
      <% if @posts.empty? %>
      <div class="post border-top p-2"> 投稿はありません </div>
      <div class="text-center mt-5 mb-5">
        <%= link_to '新規投稿', new_user_post_path(@user.nickname), class:"btn btn-primary " if current_user?(@user) %>
      </div>
      <% end %>
      <%#投稿があるとき%>
      <% @posts.map do |post| %>
      <div class="postlist border-top p-2">
        <p class="postlist-date p-0 m-0"><%= post.created_at.strftime("%Y年%m月%d日 %H時%M分") %>に投稿</p>
        <%= link_to truncate(post.title), user_post_path(@user.nickname, post.slug),class:"postlist-title" %>
        <p class="postlist-content d-inline-block"><%= truncate(post.content) %></p><!--改行を無視するため
    --><div class="buttons d-inline-block text-xl-right">
          <%# 編集ボタンは自分のページまたは公開状態であれば表示%>
          <% if current_user?(@user) || post.published %>
            <%= link_to edit_user_post_path(@user.nickname, post.slug) ,class:"btn btn-outline-success" do %>
              <i class="fa fa-edit fa-lg"></i>
            <% end %>
          <% end %>
          <%# 削除ボタンは自分のページであれば表示 %>
          <% if current_user?(@user) %>
            <%= link_to user_post_path(@user.nickname, post.slug), method: :delete ,class:"btn btn-outline-danger",data:
              {confirm: "本当に<strong>#{post.title}</strong>を削除してよろしいですか？",
              cancel: "キャンセル",
              commit: "削除する"},
              title: "削除前確認" do %>
              <i class="fa fa-trash fa-lg"></i>
            <% end %>
          <% end %>

          <div id="publicstate_form<%= post.id %>" class="d-inline-block">
            <% if post.published %>
              <%= render 'public', post: post, user: @user %>
            <%else%>
              <%= render 'unpublic', post: post, user: @user %>
            <% end %>
          </div>
        </div>

      </div>
      <% end %>
    </div>

  </div>
</div>