config/routes.rb
Rails.application.routes.draw do
  get 'inquiry/index'
  get 'inquiry/confirm'
  get 'inquiry/thanks'
  #twitter認証
  get '/auth/:provider/callback', to: 'sessions#create', as: 'auth_login'
  get '/logout', to: 'sessions#destroy'

  #静的ページRoutes
  root "static_pages#home"
  get '/terms' ,to: "static_pages#terms" 
  get '/privacy', to: "static_pages#privacy"
  
  get '/inquiry', to: 'inquiry#index'              # 入力画面
  post '/inquiry/confirm', to: 'inquiry#confirm'   # 確認画面
  post '/inquiry/thanks', to: 'inquiry#thanks'     # 送信完了画面

  #ユーザのRoutes
  resources :users, param: :nickname, only: [:new, :show, :destroy] do
    resources :posts, param: :slug do
      member do
        patch :published_true
        patch :published_false
      end
    end
  end

end

app/models/post.rb
class Post < ApplicationRecord
  before_create :set_create_slug
  belongs_to :user
  validates :user_id, presence: true #postsはuserが作成する
  
  private
    #slug発行
    def set_create_slug
      loop do
        self.slug = SecureRandom.hex(20)
        break unless Post.where(slug: slug).exists?
      end
    end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  #post投稿と削除と公開非公開切り替えは本人のみ
  before_action :logged_in_user, only: [:new, :create, :destroy, :published_false, :published_true]
  before_action :correct_user, only: [:new, :create, :destroy, :published_false, :published_true]

  def index
    @user = User.find_by(nickname: params[:user_nickname])
    @posts = @user.posts.all
  end

  def show
    @user = User.find_by(nickname: params[:user_nickname])
    @post = @user.posts.find_by(slug: params[:slug])
    @tweet_url = URI.encode(
      "http://twitter.com/intent/tweet?original_referer=" +
      request.url +
      "&url=" +
      request.url +
      "&text=" +
      " " + @post.title + " を共有します。" 
    )
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "投稿しました!"
      redirect_to user_path(current_user.nickname)
    else
      render 'new'
    end
  end

  def edit
    @user = User.find_by(nickname: params[:user_nickname])
    @post = @user.posts.find_by(slug: params[:slug])
    published_check(@post)
  end

  def update
    @user = User.find_by(nickname: params[:user_nickname])
    @post = @user.posts.find_by(slug: params[:slug])
    if @post.update_attributes(post_params)
      flash[:success] = "投稿を更新しました"
      redirect_to user_post_path(@user.nickname,@post.slug)
    else
      render 'edit'
    end
  end

  def destroy
    @post = current_user.posts.find_by(slug: params[:slug])   #ログイン中のuserのpost検索
    @post.destroy
    flash[:success] = "投稿を削除しました"
    redirect_to user_path(@post.user.nickname)
  end

  def published_true
    @user = User.find_by(nickname: params[:user_nickname])
    @post = @user.posts.find_by(slug: params[:slug])
    @post.published = true
    @post.save
    #debugger
    #Ajax用
    respond_to do |format|
      format.html { redirect_to user_path(@user.nickname) }
      format.js
    end
  end

  def published_false
    @user = User.find_by(nickname: params[:user_nickname])
    @post = @user.posts.find_by(slug: params[:slug])
    @post.published = false
    @post.save
    #Ajax用
    respond_to do |format|
      format.html { redirect_to user_path(@user.nickname) }
      format.js
    end
  end

  private
    def post_params
      params.require(:post).permit(:title, :content)
    end

    #current_userが@userと一致するか
    def correct_user
      @user = User.find_by(nickname: params[:user_nickname])
      unless current_user?(@user) then
        flash[:danger] = "あなたは#{@user.nickname}ではありません"
        redirect_to user_path(@user.nickname)
      end
    end

    #postが非公開の場合、本人以外編集させない
    def published_check(post)
      unless post.published
        unless current_user?(post.user)
          flash[:danger] = "この記事は非公開に設定されています"
          redirect_to user_path(post.user.nickname)
        end
      end
    end

end

app/helpers/posts_helper.rb
module PostsHelper
    #マークダウン用ヘルパー
    require "redcarpet"
    require "coderay"
  
    class HTMLwithCoderay < Redcarpet::Render::HTML
        def block_code(code, language)
            language = language.split(':')[0]
  
            case language.to_s
            when 'rb'
                lang = 'ruby'
            when 'yml'
                lang = 'yaml'
            when 'css'
                lang = 'css'
            when 'html'
                lang = 'html'
            when ''
                lang = 'md'
            else
                lang = language
            end
  
            CodeRay.scan(code, lang).div
        end
    end
  
    def markdown(text)
        html_render = HTMLwithCoderay.new(filter_html: true, hard_wrap: true, no_images: true)  #直リンク防止のため、画像は表示させない
        options = {
            autolink: true,
            space_after_headers: true,
            no_intra_emphasis: true,
            fenced_code_blocks: true,
            tables: true,
            hard_wrap: true,
            xhtml: true,
            lax_html_blocks: true,
            strikethrough: true
        }
        markdown = Redcarpet::Markdown.new(html_render, options)
        markdown.render(text).html_safe
    end
end

app/views/posts/_post_form.html.erb
<%= form_for(@post, url: yield(:url)) do |f| %>

  <%# f.label :content %>
  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <%# f.label :title %>
        <%= f.text_field :title , placeholder:"タイトルを記入",class:"form-control form-control-lg mt-3 mb-3" %>
        <div class="editor-title d-none">
          <span>本文</span>
        </div>
        <%= f.text_area :content, class:"form-control", placeholder:"本文を記入" %>
      </div>
    </div>

    <%# <div class="col-md-6 card">
        <div class="card-title border-bottom">プレビュー</div>
        <div class="card-text" id="preview"></div>
    </div> %>
    <%= f.submit yield(:button_text), class: "btn btn-primary ml-auto m-3" %>
  </div>

<script>
var simplemde = new SimpleMDE({hideIcons:["image"]});
</script>

<% end %>

app/views/posts/edit.html.erb
<% provide(:title, '投稿編集') %>
<% provide(:button_text, '更新') %>
<% provide(:url, user_post_path(@user.nickname, @post.slug)) %>

<%= render 'post_form' %>

app/views/posts/index.html.erb
<% @posts.all.each do |post| %>

<%= link_to post.title, user_post_path(@user.nickname,post.slug) %> , 
<%= link_to '編集', edit_user_post_path(@user.nickname,post.slug) %><br>

<% end %>
<br>

app/views/posts/new.html.erb
<% provide(:title, '新規投稿') %>
<% provide(:button_text, '投稿') %>
<% provide(:url, user_posts_path) %>
<%#<h1>New Post</h1>%>

<%= render 'post_form' %>

app/views/posts/published_false.js.erb
$("#publicstate_form<%= @post.id %>").html("<%= escape_javascript(render('users/unpublic')) %>");

app/views/posts/published_true.js.erb
$("#publicstate_form<%= @post.id %>").html("<%= escape_javascript(render('users/public')) %>");

app/views/posts/show.html.erb
<div class="post">
  <div class="post-user mb-3 ">
    <%= link_to user_path(@post.user.nickname) do %>
    <%= image_tag @post.user.image_url, alt:"profile img", class:"m-3"%>
    <span class="post-username">
      <%= @post.user.nickname %></span>
    <% end %>

    <div class="post-date d-inline-block ml-5">
      <p class="postlist-date d-inline-block m-3">
        <%= @post.created_at.strftime("%Y年%m月%d日 %H時%M分") %>に投稿</p>
      <p class="postlist-date d-inline-block m-3">
        <%= @post.updated_at.strftime("%Y年%m月%d日 %H時%M分") %>に更新</p>
    </div>
    
    <%= link_to @tweet_url ,class:"btn btn-outline-primary btn-pill pull-right mt-3" do %>
      <i class="fa fa-twitter fa-lg"></i>
    <% end %>
  </div>

  <h1 class="post-title border-bottom">
    <%= @post.title %>
  </h1>

  <div class="border-bottom">
    <div class="post-content p-3 m-3">
      <%= markdown(@post.content) %>
    </div>
  </div>

  <div class="text-xl-right">
    <%# 編集ボタンは自分のページまたは公開状態であれば表示%>
    <% if current_user?(@post.user) || @post.published %>
      <%= link_to edit_user_post_path(@post.user.nickname, @post.slug) ,class:"btn btn-outline-success mt-3 mb-3" do %>
        <i class="fa fa-edit fa-lg"></i> 編集
      <% end %>
    <% end %>
    <%# 削除ボタンと公開ボタンは自分のページでのみ表示 %>
    <% if current_user?(@post.user) %>

      <%= link_to user_post_path(@post.user.nickname, @post.slug), method: :delete ,class:"btn btn-outline-danger",data:
                  {confirm: "本当に<strong>#{@post.title}</strong>を削除してよろしいですか？",
                  cancel: "キャンセル",
                  commit: "削除する"},
                  title: "削除前確認" do %>
        <i class="fa fa-trash fa-lg"></i> 削除
      <% end %>

      <div id="publicstate_form<%= @post.id %>" class="d-inline-block">
        <% if @post.published %>
          <%= render 'users/public', post: @post, user: @post.user %>
        <%else%>
          <%= render 'users/unpublic', post: @post, user: @post.user %>
        <% end %>
      </div>

    <% end %>

  </div>


</div>