config/routes.rb
Rails.application.routes.draw do
  get 'inquiry/index'
  get 'inquiry/confirm'
  get 'inquiry/thanks'
  #twitter認証
  get '/auth/:provider/callback', to: 'sessions#create', as: 'auth_login'
  get '/logout', to: 'sessions#destroy'

  #静的ページRoutes
  root "static_pages#home"
  get '/terms' ,to: "static_pages#terms" 
  get '/privacy', to: "static_pages#privacy"
  
  get '/inquiry', to: 'inquiry#index'              # 入力画面
  post '/inquiry/confirm', to: 'inquiry#confirm'   # 確認画面
  post '/inquiry/thanks', to: 'inquiry#thanks'     # 送信完了画面

  #ユーザのRoutes
  resources :users, param: :nickname, only: [:new, :show, :destroy] do
    resources :posts, param: :slug do
      member do
        patch :published_true
        patch :published_false
      end
    end
  end

end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, presence: {message: '名前を入力してください'}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: {message: 'メールアドレスを入力してください'},
                    format: {with: VALID_EMAIL_REGEX, message: 'そのメールアドレスは有効ではありません' }
                    
end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  def index
    # 入力画面を表示
    @inquiry = Inquiry.new
    render :action => 'index'
  end

  def confirm
    # 入力値のチェック
    @inquiry = Inquiry.new(inquiry_params)

    if verify_recaptcha(model: @inquiry) && @inquiry.valid?
      # OK。確認画面を表示
      render :action => 'confirm'
    else
      # NG。入力画面を再表示
      render :action => 'index'
    end
  end

  def thanks
    # メール送信
    @inquiry = Inquiry.new(inquiry_params)
    InquiryMailer.received_email(@inquiry).deliver

    # 完了画面を表示
    render :action => 'thanks'
  end

  private
    
    def inquiry_params
      params.require(:inquiry).permit(:name, :email, :message)
    end
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/views/inquiry/confirm.html.erb
<% @page_title = 'お問い合わせ内容確認' %>
<div class="inquiry-wrapper">
  <div class="page-title text-center p-5">
    <h1>お問い合わせ：確認</h1>
  </div>
  <div class="content text-left">
    <%= form_for @inquiry, :url => inquiry_thanks_path do |f| %>
    <div class="row inquiry-form mx-auto">
          <%= f.label :name ,class:"col-md-4"%>
          <%= f.hidden_field :name %><div class="col-md-8 mb-4"><%= @inquiry.name %></div>

          <%= f.label :email ,class:"col-md-4"%>
          <%= f.hidden_field :email %><div class="col-md-8 mb-4"><%= @inquiry.email %></div>

          <%= f.label :message ,class:"col-md-4"%>
          <%= f.hidden_field :message %><div class="message-confirm col-md-8"><%= @inquiry.message %></div>

      <%= button_tag type:"submit", class: 'btn btn-success m-3' do %>
        <i class="fa fa-envelope"></i> 送信
      <% end %>
    </div>
    <% end %>
  </div>
</div>

app/views/inquiry/index.html.erb
<% @page_title = 'お問い合わせ' %>
<div class="inquiry-wrapper">
  <div class="page-title wf-nicomoji text-center m-5">
    <h1>Contact</h1>
  </div>
  <div class="content">
    <%= form_for @inquiry, :url => inquiry_confirm_path do |f| %>
      <% if @inquiry.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <strong>入力内容にエラーがあります</strong>
          <ul>
            <% @inquiry.errors.each do |attr, msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="inquiry-form mx-auto">

          <%= f.label :name %> <span class="badge mr-3 badge-squared badge-danger">必須</span>
          <%= f.text_field :name, class: 'form-control mb-4' %>

          <%= f.label :email %> <span class="badge mr-3 badge-squared badge-danger">必須</span>
          <%= f.text_field :email, class: 'form-control mb-4' %>

          <%= f.label :message %> <span class="badge mr-3 badge-squared badge-danger">必須</span>
          <%= f.text_area :message, class: 'form-control mb-4', rows: '6' %>
          <%= recaptcha_tags %>
          <%= button_tag type:"submit", class: 'btn btn-success mt-4 mb-3' do %>
            <i class="fa fa-envelope"></i> 送信
          <% end %>
      </div>

    <% end %>
  </div>
</div>

app/views/inquiry/thanks.html.erb
<div class="thanks-wrapper text-center">
  <div class="thanks-title">
    <h1 class="pt-5 pb-3">お問い合わせ：送信しました</h1>
  </div>
  <div class="content">
    <p class="pb-5">お問い合わせありがとうございます。</p>
  </div>
</div>