config/routes.rb
Rails.application.routes.draw do
  get 'inquiry/index'
  get 'inquiry/confirm'
  get 'inquiry/thanks'
  #twitter認証
  get '/auth/:provider/callback', to: 'sessions#create', as: 'auth_login'
  get '/logout', to: 'sessions#destroy'

  #静的ページRoutes
  root "static_pages#home"
  get '/terms' ,to: "static_pages#terms" 
  get '/privacy', to: "static_pages#privacy"
  
  get '/inquiry', to: 'inquiry#index'              # 入力画面
  post '/inquiry/confirm', to: 'inquiry#confirm'   # 確認画面
  post '/inquiry/thanks', to: 'inquiry#thanks'     # 送信完了画面

  #ユーザのRoutes
  resources :users, param: :nickname, only: [:new, :show, :destroy] do
    resources :posts, param: :slug do
      member do
        patch :published_true
        patch :published_false
      end
    end
  end

end

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
<% fa = {"info" => "info", "success" => "check", "warning" => "warning", "danger" => "exclamation-circle" } %>
<div class="alert alert-<%= message_type %> alert-dismissible fade show" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">×</span>
  </button>
  <i class="fa fa-<%= fa[message_type] %>"></i>
  <%= message %>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer bg-dark">
    <ul class="text-center list-inline">
      <li class="list-inline-item"><%= link_to "利用規約", terms_path %></li>
      <li class="list-inline-item"><%= link_to "プライバシーポリシー", privacy_path %></li>
      <li class="list-inline-item"><%= link_to "お問い合わせ", inquiry_path %></li>
    </ul>
    <p class="copyright text-center">Copyright &copy; Unio All rights reserved.</p>
</footer>

app/views/layouts/_header.html.erb
      <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <div class="container">
          <%= link_to root_path, id: "logo" ,class:"navbar-brand wf-nicomoji" do %>
            <i class="fa fa-inbox fa-lg"></i> Draft Box<span class="logo-dot">.</span>
          <% end %>


          <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNav">

            <ul class="navbar-nav ml-auto">
              <% if logged_in? %>
              <li class="nav-item"><%= link_to current_user.nickname, user_path(current_user.nickname),class:"nav-link" %></li>
                <li class="nav-item dropdown show">
                    <%= image_tag current_user.image_url ,class:"nav-link dropdown-toggle", data:{toggle:"dropdown"} ,size:"50x50"%>
                    <ul class="dropdown-menu" role="menu">
                      <li><%= link_to 'マイページ', user_path(current_user.nickname), class:"dropdown-item" %></li>
                      <li><%= link_to 'ログアウト', logout_url, class:"dropdown-item"%></li>
                    </ul>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to 'Login', '/auth/twitter', class:"nav-link"%>
                </li>
              <% end %>
            </ul>

          </div>
        </div>
      </nav>  
    </header>

app/views/layouts/_rails_default.html.erb
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8"/>
  <title>
    <%= full_title(yield(:title)) %>
  </title>
  <link href="https://fonts.googleapis.com/earlyaccess/nicomoji.css" rel="stylesheet" />
  <%= render 'layouts/rails_default' %>
  <%= render 'layouts/shim' %>
  <%= favicon_link_tag('favicon.ico') %>
</head>

<body>
  <%# Header %>
  <%= render 'layouts/header' %>

  <%# flashメッセージ %>
  <% unless flash.empty? %>
    <%= render 'layouts/flash' %>
  <% end %>

  <div class="container-wrapper bg-light">
    <div class="container bg-white">

      <%# 本コンテンツ %>
      <%= yield %>

    </div>
  </div>

  <%# Footer %>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</body>

</html>